# (Github Dark) Colors for Alacritty

[colors.primary]
background = "#30363d"
foreground = "#e6edf3"

[colors.cursor]
text = "#30363d"
cursor = "#e6edf3"

[colors.normal]
black = "#484f58"
red = "#ff7b72"
green = "#3fb950"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

[colors.bright]
black = "#6e7681"
red = "#ffa198"
green = "#56d364"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"
